name: attDL
channels:
  - conda-forge
  - defaults
dependencies:
  - gast=0.3.*
  - imageio=2.8.*
  - ipykernel=5.4.*
  - ipython=7.19.*
  - ipywidgets=7.6.*
  - matplotlib=3.4.*
  - nbformat=5.1.*
  - notebook=6.0.*
  - numpy=1.19.*
  - pandas=1.2.*
  - pip=21.1.*
  - python=3.7.*
  - scikit-learn=0.24.*
  - scipy=1.4.*
  - seaborn=0.11.*
  - statsmodels=0.12.*
  - tensorflow=2.4.*
  - tqdm=4.56
  - pip:
    - watermark==2.0.2
    - kats==0.1.0
    - tsmoothie==0.2.0
    - pykalman==0.9.5
    - holidays==0.10.3
    - autopep8==1.5.7
